version: '3.8'

services:
  nuxt:
    build: .
    container_name: nuxt
    restart: unless-stopped
    tty: true
    ports:
      - '24678:24678'
      - '9222:9222'
      - '5454:5555'
    environment:
      - NODE_ENV
    volumes:
      - .:/app
    command: sh -c "chmod +x ./bin/check_env.sh && ./bin/check_env.sh"
    networks:
      - nuxt-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - '${APP_PORT-80}:80'
      - '443:443'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nuxt
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
